// Generated by gencpp from file sen_one/GetDistance.msg
// DO NOT EDIT!


#ifndef SEN_ONE_MESSAGE_GETDISTANCE_H
#define SEN_ONE_MESSAGE_GETDISTANCE_H

#include <ros/service_traits.h>


#include <sen_one/GetDistanceRequest.h>
#include <sen_one/GetDistanceResponse.h>


namespace sen_one
{

struct GetDistance
{

typedef GetDistanceRequest Request;
typedef GetDistanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetDistance
} // namespace sen_one


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sen_one::GetDistance > {
  static const char* value()
  {
    return "05f9280a5bbafe8052386937af843453";
  }

  static const char* value(const ::sen_one::GetDistance&) { return value(); }
};

template<>
struct DataType< ::sen_one::GetDistance > {
  static const char* value()
  {
    return "sen_one/GetDistance";
  }

  static const char* value(const ::sen_one::GetDistance&) { return value(); }
};


// service_traits::MD5Sum< ::sen_one::GetDistanceRequest> should match
// service_traits::MD5Sum< ::sen_one::GetDistance >
template<>
struct MD5Sum< ::sen_one::GetDistanceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sen_one::GetDistance >::value();
  }
  static const char* value(const ::sen_one::GetDistanceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sen_one::GetDistanceRequest> should match
// service_traits::DataType< ::sen_one::GetDistance >
template<>
struct DataType< ::sen_one::GetDistanceRequest>
{
  static const char* value()
  {
    return DataType< ::sen_one::GetDistance >::value();
  }
  static const char* value(const ::sen_one::GetDistanceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sen_one::GetDistanceResponse> should match
// service_traits::MD5Sum< ::sen_one::GetDistance >
template<>
struct MD5Sum< ::sen_one::GetDistanceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sen_one::GetDistance >::value();
  }
  static const char* value(const ::sen_one::GetDistanceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sen_one::GetDistanceResponse> should match
// service_traits::DataType< ::sen_one::GetDistance >
template<>
struct DataType< ::sen_one::GetDistanceResponse>
{
  static const char* value()
  {
    return DataType< ::sen_one::GetDistance >::value();
  }
  static const char* value(const ::sen_one::GetDistanceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEN_ONE_MESSAGE_GETDISTANCE_H
