// Generated by gencpp from file sen_one/GetDistanceRequest.msg
// DO NOT EDIT!


#ifndef SEN_ONE_MESSAGE_GETDISTANCEREQUEST_H
#define SEN_ONE_MESSAGE_GETDISTANCEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sen_one
{
template <class ContainerAllocator>
struct GetDistanceRequest_
{
  typedef GetDistanceRequest_<ContainerAllocator> Type;

  GetDistanceRequest_()
    : obstacle_name()  {
    }
  GetDistanceRequest_(const ContainerAllocator& _alloc)
    : obstacle_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _obstacle_name_type;
  _obstacle_name_type obstacle_name;





  typedef boost::shared_ptr< ::sen_one::GetDistanceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sen_one::GetDistanceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetDistanceRequest_

typedef ::sen_one::GetDistanceRequest_<std::allocator<void> > GetDistanceRequest;

typedef boost::shared_ptr< ::sen_one::GetDistanceRequest > GetDistanceRequestPtr;
typedef boost::shared_ptr< ::sen_one::GetDistanceRequest const> GetDistanceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sen_one::GetDistanceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sen_one::GetDistanceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sen_one::GetDistanceRequest_<ContainerAllocator1> & lhs, const ::sen_one::GetDistanceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.obstacle_name == rhs.obstacle_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sen_one::GetDistanceRequest_<ContainerAllocator1> & lhs, const ::sen_one::GetDistanceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sen_one

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sen_one::GetDistanceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sen_one::GetDistanceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sen_one::GetDistanceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sen_one::GetDistanceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sen_one::GetDistanceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sen_one::GetDistanceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sen_one::GetDistanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be1636c432e60a923a857d0fb7b3385b";
  }

  static const char* value(const ::sen_one::GetDistanceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe1636c432e60a92ULL;
  static const uint64_t static_value2 = 0x3a857d0fb7b3385bULL;
};

template<class ContainerAllocator>
struct DataType< ::sen_one::GetDistanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sen_one/GetDistanceRequest";
  }

  static const char* value(const ::sen_one::GetDistanceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sen_one::GetDistanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string obstacle_name\n"
;
  }

  static const char* value(const ::sen_one::GetDistanceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sen_one::GetDistanceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obstacle_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetDistanceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sen_one::GetDistanceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sen_one::GetDistanceRequest_<ContainerAllocator>& v)
  {
    s << indent << "obstacle_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.obstacle_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEN_ONE_MESSAGE_GETDISTANCEREQUEST_H
