// Generated by gencpp from file distance_calculator/GetDistance.msg
// DO NOT EDIT!


#ifndef DISTANCE_CALCULATOR_MESSAGE_GETDISTANCE_H
#define DISTANCE_CALCULATOR_MESSAGE_GETDISTANCE_H

#include <ros/service_traits.h>


#include <distance_calculator/GetDistanceRequest.h>
#include <distance_calculator/GetDistanceResponse.h>


namespace distance_calculator
{

struct GetDistance
{

typedef GetDistanceRequest Request;
typedef GetDistanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetDistance
} // namespace distance_calculator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::distance_calculator::GetDistance > {
  static const char* value()
  {
    return "77f540a9cfbaeedc83618fe997a13644";
  }

  static const char* value(const ::distance_calculator::GetDistance&) { return value(); }
};

template<>
struct DataType< ::distance_calculator::GetDistance > {
  static const char* value()
  {
    return "distance_calculator/GetDistance";
  }

  static const char* value(const ::distance_calculator::GetDistance&) { return value(); }
};


// service_traits::MD5Sum< ::distance_calculator::GetDistanceRequest> should match
// service_traits::MD5Sum< ::distance_calculator::GetDistance >
template<>
struct MD5Sum< ::distance_calculator::GetDistanceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::distance_calculator::GetDistance >::value();
  }
  static const char* value(const ::distance_calculator::GetDistanceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::distance_calculator::GetDistanceRequest> should match
// service_traits::DataType< ::distance_calculator::GetDistance >
template<>
struct DataType< ::distance_calculator::GetDistanceRequest>
{
  static const char* value()
  {
    return DataType< ::distance_calculator::GetDistance >::value();
  }
  static const char* value(const ::distance_calculator::GetDistanceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::distance_calculator::GetDistanceResponse> should match
// service_traits::MD5Sum< ::distance_calculator::GetDistance >
template<>
struct MD5Sum< ::distance_calculator::GetDistanceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::distance_calculator::GetDistance >::value();
  }
  static const char* value(const ::distance_calculator::GetDistanceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::distance_calculator::GetDistanceResponse> should match
// service_traits::DataType< ::distance_calculator::GetDistance >
template<>
struct DataType< ::distance_calculator::GetDistanceResponse>
{
  static const char* value()
  {
    return DataType< ::distance_calculator::GetDistance >::value();
  }
  static const char* value(const ::distance_calculator::GetDistanceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DISTANCE_CALCULATOR_MESSAGE_GETDISTANCE_H
