// Generated by gencpp from file distance_calculator/GetDistanceResponse.msg
// DO NOT EDIT!


#ifndef DISTANCE_CALCULATOR_MESSAGE_GETDISTANCERESPONSE_H
#define DISTANCE_CALCULATOR_MESSAGE_GETDISTANCERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace distance_calculator
{
template <class ContainerAllocator>
struct GetDistanceResponse_
{
  typedef GetDistanceResponse_<ContainerAllocator> Type;

  GetDistanceResponse_()
    : distance(0.0)  {
    }
  GetDistanceResponse_(const ContainerAllocator& _alloc)
    : distance(0.0)  {
  (void)_alloc;
    }



   typedef double _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::distance_calculator::GetDistanceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::distance_calculator::GetDistanceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetDistanceResponse_

typedef ::distance_calculator::GetDistanceResponse_<std::allocator<void> > GetDistanceResponse;

typedef boost::shared_ptr< ::distance_calculator::GetDistanceResponse > GetDistanceResponsePtr;
typedef boost::shared_ptr< ::distance_calculator::GetDistanceResponse const> GetDistanceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::distance_calculator::GetDistanceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::distance_calculator::GetDistanceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::distance_calculator::GetDistanceResponse_<ContainerAllocator1> & lhs, const ::distance_calculator::GetDistanceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::distance_calculator::GetDistanceResponse_<ContainerAllocator1> & lhs, const ::distance_calculator::GetDistanceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace distance_calculator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::distance_calculator::GetDistanceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::distance_calculator::GetDistanceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::distance_calculator::GetDistanceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::distance_calculator::GetDistanceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::distance_calculator::GetDistanceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::distance_calculator::GetDistanceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::distance_calculator::GetDistanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acff7fda0c683c872875f5c4b069f124";
  }

  static const char* value(const ::distance_calculator::GetDistanceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xacff7fda0c683c87ULL;
  static const uint64_t static_value2 = 0x2875f5c4b069f124ULL;
};

template<class ContainerAllocator>
struct DataType< ::distance_calculator::GetDistanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "distance_calculator/GetDistanceResponse";
  }

  static const char* value(const ::distance_calculator::GetDistanceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::distance_calculator::GetDistanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 distance \n"
;
  }

  static const char* value(const ::distance_calculator::GetDistanceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::distance_calculator::GetDistanceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetDistanceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::distance_calculator::GetDistanceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::distance_calculator::GetDistanceResponse_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DISTANCE_CALCULATOR_MESSAGE_GETDISTANCERESPONSE_H
